### ISSUE TITLE
[cudapoa] keep member type and allocation size in sync

### ISSUE THREAD

**Issue by tijyojwad** [clara-parabricks/ClaraGenomicsAnalysis#396]
The way cudapoa allocates buffers right now is by calculating the size based on type of the struct elements. However, the sizing calculation uses the type explicitly instead of drawing it from the member element directly. This means the type has to be specified in two places, and more importantly updated in two places concurrently, which is the source of many problems.

It would be a good idea to use something like http://www.cplusplus.com/reference/typeinfo/type_info/name/ to keep the types in sync so they only need to be updated in one place.

**Comment by ahehn-nv** [comment]
Could you elaborate on the problem a bit? Right now, I doubt that typeinfo is the right tool.

**Comment by tijyojwad** [comment]
@ahehn-nv here's an example of the problem - 

Struct member defined here - https://github.com/clara-genomics/ClaraGenomicsAnalysis/blob/dev-v0.5.0/cudapoa/src/cudapoa_kernels.cuh#L113

The allocation is done here - https://github.com/clara-genomics/ClaraGenomicsAnalysis/blob/dev-v0.5.0/cudapoa/src/allocate_block.hpp#L224

So we want to keep the types in sync. I realize `typeinfo` isn't the right one (I briefly looked at it), but maybe `decltype` is better for it?

P.S. This aside, the allocation in cudapoa can also do with an overhaul with our new alocator classes and so on.

**Comment by tijyojwad** [comment]
@ahehn-nv - I was being daft and overthinking it. `sizeof(variable_name)` would work just fine for this problem.

**Comment by ahehn-nv** [comment]
Yes, that sounds better. :+1:
