### ISSUE TITLE
[cudapoa] Error code 8 on some cases of Bonito sample

### ISSUE THREAD

**Issue by tijyojwad** [clara-parabricks/ClaraGenomicsAnalysis#398]
In bonito sample dataset, for about 7 cases, generate consensus in `cudapoa` fails to run successfully. It exits with Error code 8. Would be helpful to investigate why it fails, whether it's a bug or not, and how to fix.

**Comment by atadkase** [comment]
Chased down the error to this line: https://github.com/clara-genomics/ClaraGenomicsAnalysis/blob/dev-v0.5.0/cudapoa/src/cudapoa_nw_banded.cu#L465
Looking at why the upper bound is getting exceeded now.
